### ISSUE TITLE
CSSSelector and XPath Labels

### ISSUE THREAD

**Issue by elescamilla** [lanl/Memento-Tracer-Extention#10]
As it currently stands, these are the terms used differentiate 2 selection options. However, they do not convey to the non-technical user which option they should pick.

For this issue, 
* look into other wording options
* indicate to the user which option is preferred (CSSSelector)

**Comment by luda171** [comment]
It defaults to CSSselector as the preferred option.  We could not fully determine the optimum selector by machine, so the user needs to consider which option is better for her particular case, as in some cases you need to select XPath. I would add help pop up with an explanation.

**Comment by elescamilla** [comment]
I agree. I think a help pop up with an explanation would be a great solution to this.

**Comment by talyacooper** [comment]
Closed--we have addressed this issue (hopefully) by adding help text
