### ISSUE TITLE
Rename "End condition"

### ISSUE THREAD

**Issue by elescamilla** [lanl/Memento-Tracer-Extention#12]
When the user selects "click multi" they are prompted to choose an "end condition". However, this terminology should be updated to reflect the functionality.

Definition of Done: Replace "end condition" with another phrase

**Comment by talyacooper** [comment]
wondering if the same applies to "Exit Condition" for the Click Until submenu, or if this is clear enough to an end user?

**Comment by talyacooper** [comment]
Some ideas for this: 

End loop cycle
Stop condition
Break sign
Breakpoint
Loop breaker
Return condition
