### ISSUE TITLE
add cancel/stop button to the tracer demo site

### ISSUE THREAD

**Issue by talyacooper** [lanl/Memento-Tracer-Extention#4]
Allow someone using the GUI to stop/cancel a trace in progress and remove a trace from the queue. This will be helpful for traces that are taking a long time or for traces that were submitted erroneously.

**Comment by talyacooper** [comment]
visual indication that a trace is running would be helpful as well

**Comment by martinklein0815** [comment]
Just a note to clarify that this is not related to the browser extension but to the TracerDemo web service.

**Comment by talyacooper** [comment]
@martinklein0815 should I close this issue and add it to the other GH page?

**Comment by talyacooper** [comment]
closed, addressed on the Tracer repo
