### ISSUE TITLE
Modify "click all links in area" label

### ISSUE THREAD

**Issue by elescamilla** [lanl/Memento-Tracer-Extention#7]
"Click all links in area" may not be the best description for what this actually does. 

For this issue,
1. Investigate what the option does
2. Propose a different label
3. Implement a label change

**Comment by martinklein0815** [comment]
Is this just a wording issue or is there more to it?

**Comment by elescamilla** [comment]
@martinklein0815 Correct, this is a wording change

**Comment by talyacooper** [comment]
Some ideas for this: 

Click all at once
Click group at once
Download links in group
Capture group of links
Click group of links
Click all simultaneously (Click group simultaneously)
