### ISSUE TITLE
Restart selection

### ISSUE THREAD

**Issue by elescamilla** [lanl/Memento-Tracer-Extention#9]
When the user incorrectly selects an item, the current implementation requires them to save the event, delete it from the hierarchy, and create a new event. Ideally, the user will be able to restart the selection without leaving the "create event" form.

Definition of done: the user is able to select an element on the page, clear the selection, and select another element on the page.

**Comment by talyacooper** [comment]
I believe this is redundant with issue #2 but just want @elescamilla to confirm--if so I'll close that issue

**Comment by elescamilla** [comment]
Correct. This is redundant with issue #2 . I apologize that I didn't notice that earlier

**Comment by martinklein0815** [comment]
@elescamilla this looks like a good one to start with also
